import React, { useState, useRef, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Mic, ChevronLeft, Undo2, Redo2, Code2, Settings2, X, Save,
  Volume2, VolumeX, GripVertical, Loader2, Crown, Zap, Download,
  Copy, Check, AlertCircle, RefreshCw
} from 'lucide-react';
import { toast } from 'sonner';
import DOMPurify from 'dompurify';

// ─── API Base URL ─────────────────────────────────────────────────────────────
const API_BASE = (import.meta as any).env?.VITE_API_URL || 'http://127.0.0.1:5000';

// ─── Types ────────────────────────────────────────────────────────────────────
interface WorkspaceProps {
  onBack: () => void;
  projectId?: string | null;
}

interface CanvasComponent {
  id: string;
  type: string;
  name: string;
  styles: Record<string, string>;
  htmlContent: string;
}

const FREE_TIER_LIMIT = 10;

// ─── Sanitize HTML — DOMPurify, defense-in-depth before dangerouslySetInnerHTML ─
// Server already sanitizes AI output; this re-sanitizes on render in case stale or
// tampered canvas state reaches the DOM.
const sanitizeHTML = (html: string): string => {
  if (!html) return '';
  return DOMPurify.sanitize(html, {
    FORBID_TAGS: ['script', 'iframe', 'object', 'embed', 'link', 'meta', 'base'],
    ALLOW_DATA_ATTR: false,
  });
};

// ─── Export Code Modal ────────────────────────────────────────────────────────
const ExportModal: React.FC<{
  canvas: CanvasComponent[];
  projectTitle: string;
  onClose: () => void;
  userTier: 'free' | 'premium';
  onUpgrade: () => void;
  isUpgrading: boolean;
}> = ({ canvas, projectTitle, onClose, userTier, onUpgrade, isUpgrading }) => {
  const [copied, setCopied] = useState(false);
  const isPremium = userTier === 'premium';

  const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${projectTitle}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
</head>
<body>
${canvas.map(c => `  <!-- ${c.name} -->\n  ${c.htmlContent.trim()}`).join('\n\n')}
</body>
</html>`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(fullHTML);
    setCopied(true);
    toast.success('Code copied to clipboard!');
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadHTML = () => {
    const blob = new Blob([fullHTML], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectTitle.replace(/\s+/g, '-').toLowerCase() || 'speak2design'}.html`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('HTML file downloaded!');
  };

  const handleDownloadCSS = () => {
    const cssContent = `/* Generated by Speak2Design — https://speak2design.vercel.app */
/* This project uses Tailwind CSS utility classes. */
/* Add the Tailwind CDN or install via npm for production use. */

body {
  margin: 0;
  font-family: 'Inter', -apple-system, sans-serif;
}
`;
    const blob = new Blob([cssContent], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'styles.css';
    a.click();
    URL.revokeObjectURL(url);
    toast.success('CSS file downloaded!');
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col"
      >
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <div>
            <h2 className="font-bold text-xl text-gray-900">Export Code</h2>
            <p className="text-xs text-gray-500 mt-0.5">
              {canvas.length} component{canvas.length !== 1 ? 's' : ''} · Production-ready HTML + Tailwind CSS
            </p>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-xl transition-colors text-gray-500">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex-1 overflow-auto bg-[#0d1117] m-4 rounded-xl relative">
          <div className="absolute top-3 right-3 flex items-center gap-1 px-2 py-1 bg-white/10 rounded-lg text-[10px] text-white/60 font-mono">
            index.html
          </div>
          <pre className="text-green-400 font-mono text-xs p-6 overflow-auto leading-relaxed whitespace-pre-wrap">
            {fullHTML}
          </pre>
        </div>

        <div className="px-6 py-4 border-t border-gray-100 flex flex-wrap gap-3 items-center">
          <button
            onClick={handleCopy}
            className={`flex items-center gap-2 px-5 py-2.5 rounded-xl font-bold text-sm transition-all ${
              copied ? 'bg-green-500 text-white' : 'bg-gray-900 text-white hover:bg-gray-700'
            }`}
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied!' : 'Copy Code'}
          </button>
          {isPremium ? (
            <>
              <button
                onClick={handleDownloadHTML}
                className="flex items-center gap-2 px-5 py-2.5 bg-[#0052CC] hover:bg-[#0047b3] text-white rounded-xl font-bold text-sm transition-all"
              >
                <Download className="w-4 h-4" /> Download HTML
              </button>
              <button
                onClick={handleDownloadCSS}
                className="flex items-center gap-2 px-5 py-2.5 bg-white border border-gray-200 text-gray-700 rounded-xl font-bold text-sm hover:bg-gray-50 transition-all"
              >
                <Download className="w-4 h-4" /> Download CSS
              </button>
              <div className="ml-auto flex items-center gap-1 text-xs text-gray-400">
                <Check className="w-3.5 h-3.5 text-green-500" />
                Tailwind CDN included
              </div>
            </>
          ) : (
            <div className="flex items-center gap-3 w-full">
              <div className="flex items-center gap-2 text-xs text-amber-700 bg-amber-50 border border-amber-200 px-3 py-2 rounded-xl">
                <Crown className="w-3.5 h-3.5 text-amber-500" />
                File downloads (HTML/CSS) are a Premium feature. Free plan can copy code.
              </div>
              <button
                onClick={onUpgrade}
                disabled={isUpgrading}
                className="ml-auto flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-xl font-bold text-sm hover:opacity-90 transition-all disabled:opacity-60"
              >
                {isUpgrading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Crown className="w-4 h-4" />}
                {isUpgrading ? 'Upgrading…' : 'Upgrade to Download'}
              </button>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
};

// ─── Workspace Component ───────────────────────────────────────────────────────
export const Workspace: React.FC<WorkspaceProps> = ({ onBack, projectId }) => {
  const [isListening, setIsListening] = useState(false);
  const [transcription, setTranscription] = useState('');
  const [language, setLanguage] = useState<'English' | 'Urdu'>('English');
  const [textCommand, setTextCommand] = useState('');
  const [isProcessingAI, setIsProcessingAI] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [ttsEnabled, setTtsEnabled] = useState(true);
  const [usageCount, setUsageCount] = useState(0);
  const [userTier, setUserTier] = useState<'free' | 'premium'>('free');
  const [showExportModal, setShowExportModal] = useState(false);
  const [isUpgrading, setIsUpgrading] = useState(false);
  const [clarificationMessage, setClarificationMessage] = useState<string | null>(null);

  const [canvasState, setCanvasState] = useState<CanvasComponent[]>([]);
  const [historyStack, setHistoryStack] = useState<CanvasComponent[][]>([]);
  const [historyPointer, setHistoryPointer] = useState(-1);
  const [selectedComponentId, setSelectedComponentId] = useState<string | null>(null);
  const [dragOverId, setDragOverId] = useState<string | null>(null);
  const [projectTitle, setProjectTitle] = useState('Untitled Project');

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);
  const dragItemRef = useRef<string | null>(null);

  // ── Load user tier + usageCount from DB (not stale client state) ────────────
  useEffect(() => {
    const loadUserProfile = async () => {
      try {
        const token = localStorage.getItem('speak2design_token');
        if (!token) return;
        const res = await fetch(`${API_BASE}/api/auth/profile`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        const data = await res.json();
        if (data.success && data.user) {
          setUsageCount(data.user.usageCount || 0);
          setUserTier(data.user.tier || 'free');
        }
      } catch (err) {
        console.error('Profile load error:', err);
      }
    };
    loadUserProfile();
  }, []);

  // ── Load project ─────────────────────────────────────────────────────────────
  useEffect(() => {
    if (!projectId) return;
    const loadProject = async () => {
      try {
        const token = localStorage.getItem('speak2design_token');
        const res = await fetch(`${API_BASE}/api/projects/${projectId}`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        const data = await res.json();
        if (data.success && data.project) {
          const proj = data.project;
          setProjectTitle(proj.title || 'Untitled Project');
          if (proj.language) setLanguage(proj.language);
          if (proj.canvasState?.length > 0) {
            setCanvasState(proj.canvasState);
            setHistoryStack([proj.canvasState]);
            setHistoryPointer(0);
          }
        }
      } catch (err) {
        console.error('Project load error:', err);
      }
    };
    loadProject();
  }, [projectId]);

  // ── TTS ──────────────────────────────────────────────────────────────────────
  const speakTTS = useCallback((text: string) => {
    if (!ttsEnabled || !window.speechSynthesis) return;
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = language === 'Urdu' ? 'ur-PK' : 'en-US';
    // Prefer a matching installed voice when available
    const match = window.speechSynthesis.getVoices().find(v => v.lang === utterance.lang);
    if (match) utterance.voice = match;
    utterance.rate = 1.05;
    utterance.pitch = 1.0;
    window.speechSynthesis.speak(utterance);
  }, [ttsEnabled, language]);

  // ── History ──────────────────────────────────────────────────────────────────
  const pushNewStateToHistory = (nextState: CanvasComponent[]) => {
    const updated = historyStack.slice(0, historyPointer + 1);
    updated.push(nextState);
    setHistoryStack(updated);
    setHistoryPointer(updated.length - 1);
    setCanvasState(nextState);
  };

  const handleUndoAction = () => {
    if (historyPointer > 0) {
      const p = historyPointer - 1;
      setHistoryPointer(p);
      setCanvasState(historyStack[p]);
      setSelectedComponentId(null);
      toast.info('Undo applied.');
      speakTTS('Undo applied.');
    }
  };

  const handleRedoAction = () => {
    if (historyPointer < historyStack.length - 1) {
      const p = historyPointer + 1;
      setHistoryPointer(p);
      setCanvasState(historyStack[p]);
      setSelectedComponentId(null);
      toast.info('Redo applied.');
      speakTTS('Redo applied.');
    }
  };

  // ── Save ─────────────────────────────────────────────────────────────────────
  const handleSaveProject = async () => {
    if (!projectId) { toast.error('No project ID — create from Dashboard first.'); return; }
    setIsSaving(true);
    try {
      const token = localStorage.getItem('speak2design_token');
      const res = await fetch(`${API_BASE}/api/projects/${projectId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ canvasState, title: projectTitle, language })
      });
      const data = await res.json();
      if (data.success) {
        toast.success('Project saved!');
        speakTTS('Project saved successfully.');
      } else {
        toast.error('Save failed: ' + data.message);
      }
    } catch {
      toast.error('Could not reach server.');
    } finally {
      setIsSaving(false);
    }
  };

  // ── FR_09: upgrade to Premium (unlocks export downloads + publishing) ──────
  const handleUpgrade = async () => {
    setIsUpgrading(true);
    try {
      const token = localStorage.getItem('speak2design_token');
      const res = await fetch(`${API_BASE}/api/auth/upgrade`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await res.json();
      if (data.success) {
        setUserTier('premium');
        toast.success('Upgraded to Premium! Downloads and publishing unlocked.');
        speakTTS('You are now a Premium user.');
      } else {
        toast.error(data.message || 'Upgrade failed.');
      }
    } catch {
      toast.error('Connection error during upgrade.');
    } finally {
      setIsUpgrading(false);
    }
  };

  // ── Handle API response (shared between voice and text) ───────────────────
  const handleAPIResponse = (data: any) => {
    // Sync usage stats from authoritative server response
    if (typeof data.usageCount === 'number') setUsageCount(data.usageCount);
    if (data.tier) setUserTier(data.tier);

    if (data.clarification_needed) {
      setClarificationMessage(data.message);
      toast.info(data.message, { duration: 6000 });
      if (data.ttsConfirmation) speakTTS(data.ttsConfirmation);
      return;
    }

    setClarificationMessage(null);

    if (data.updatedCanvas && Array.isArray(data.updatedCanvas)) {
      pushNewStateToHistory(data.updatedCanvas);
      // FR_06: notify when the latest command overrode an existing component.
      if (data.overrideNotice) {
        toast.warning(data.overrideNotice, { duration: 5000 });
        speakTTS(data.overrideNotice);
      } else {
        toast.success('Canvas updated!');
        if (data.ttsConfirmation) speakTTS(data.ttsConfirmation);
      }
    }
  };

  // ── Voice recording ───────────────────────────────────────────────────────
  const activateAudioCaptureStream = async () => {
    if (userTier === 'free' && usageCount >= FREE_TIER_LIMIT) {
      toast.error(`Free tier limit reached (${FREE_TIER_LIMIT} commands). Upgrade to Premium.`, { duration: 5000 });
      speakTTS('Free tier limit reached. Please upgrade to Premium.');
      return;
    }
    audioChunksRef.current = [];
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mimeType = MediaRecorder.isTypeSupported('audio/webm;codecs=opus')
        ? 'audio/webm;codecs=opus'
        : MediaRecorder.isTypeSupported('audio/webm')
        ? 'audio/webm'
        : 'audio/ogg;codecs=opus';

      const recorder = new MediaRecorder(stream, { mimeType });
      mediaRecorderRef.current = recorder;
      recorder.ondataavailable = (e) => { if (e.data.size > 0) audioChunksRef.current.push(e.data); };
      recorder.onstop = async () => {
        const blob = new Blob(audioChunksRef.current, { type: mimeType });
        stream.getTracks().forEach(t => t.stop());
        if (blob.size < 1000) {
          toast.error('Recording too short — hold the button while speaking.');
          setIsListening(false);
          return;
        }
        await processAudioPayload(blob);
      };
      recorder.start(250);
      setIsListening(true);
      setTranscription('Listening… speak your layout command.');
      setClarificationMessage(null);
    } catch (err: any) {
      if (err.name === 'NotAllowedError') {
        toast.error('Microphone access denied. Allow it in browser settings.');
      } else {
        toast.error('Could not start recording: ' + err.message);
      }
    }
  };

  const terminateAudioCaptureStream = () => {
    if (mediaRecorderRef.current && mediaRecorderRef.current.state !== 'inactive') {
      mediaRecorderRef.current.stop();
      setIsListening(false);
    }
  };

  // Safety net: if the user releases the mouse/touch outside the mic button while
  // recording, stop the capture anyway so it never gets stuck in "Listening…".
  useEffect(() => {
    if (!isListening) return;
    const stop = () => terminateAudioCaptureStream();
    window.addEventListener('mouseup', stop);
    window.addEventListener('touchend', stop);
    return () => {
      window.removeEventListener('mouseup', stop);
      window.removeEventListener('touchend', stop);
    };
  }, [isListening]);

  const processAudioPayload = async (audioBlob: Blob) => {
    setIsProcessingAI(true);
    const formData = new FormData();
    formData.append('audio', audioBlob, 'prompt_capture.webm');
    formData.append('language', language);
    formData.append('currentCanvas', JSON.stringify(canvasState));
    try {
      const token = localStorage.getItem('speak2design_token');
      const res = await fetch(`${API_BASE}/api/voice/transcribe-and-generate`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` },
        body: formData
      });
      const data = await res.json();

      if (data.transcription) setTranscription(data.transcription);

      if (res.status === 403 && data.limitReached) {
        if (typeof data.usageCount === 'number') setUsageCount(data.usageCount);
        if (data.tier) setUserTier(data.tier);
        toast.error(data.message, { duration: 5000 });
        speakTTS('Free tier limit reached. Please upgrade to Premium.');
        return;
      }
      if (res.status === 429) { toast.error(data.message || 'Too many requests. Wait a moment.'); return; }
      if (res.ok && data.success) {
        handleAPIResponse(data);
      } else {
        toast.error(data.message || 'AI processing failed.');
        speakTTS('Sorry, I could not process that command. Please try again.');
      }
    } catch {
      toast.error('Network error — could not reach the AI pipeline.');
    } finally {
      setIsProcessingAI(false);
    }
  };

  // ── Text command ─────────────────────────────────────────────────────────────
  const dispatchTextCommand = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!textCommand.trim()) return;
    if (userTier === 'free' && usageCount >= FREE_TIER_LIMIT) {
      toast.error(`Free tier limit (${FREE_TIER_LIMIT} commands) reached. Upgrade to Premium.`);
      return;
    }
    setIsProcessingAI(true);
    setClarificationMessage(null);
    try {
      const token = localStorage.getItem('speak2design_token');
      const res = await fetch(`${API_BASE}/api/voice/process-text-intent`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ command: textCommand, currentCanvas: canvasState, language })
      });
      const data = await res.json();

      if (res.status === 403 && data.limitReached) {
        if (typeof data.usageCount === 'number') setUsageCount(data.usageCount);
        if (data.tier) setUserTier(data.tier);
        toast.error(data.message, { duration: 5000 });
        return;
      }
      if (res.status === 429) { toast.error(data.message || 'Too many requests. Wait a moment.'); return; }
      if (res.ok && data.success) {
        handleAPIResponse(data);
        setTextCommand('');
      } else {
        toast.error(data.message || 'Command failed.');
      }
    } catch {
      toast.error('Connection error.');
    } finally {
      setIsProcessingAI(false);
    }
  };

  // ── Remove component ─────────────────────────────────────────────────────────
  const removeComponent = (id: string) => {
    const updated = canvasState.filter(c => c.id !== id);
    pushNewStateToHistory(updated);
    setSelectedComponentId(null);
    toast.info('Component removed.');
    speakTTS('Component removed from canvas.');
  };

  // ── Drag & drop reorder ──────────────────────────────────────────────────────
  const handleDragStart = (id: string) => { dragItemRef.current = id; };
  const handleDragOver = (e: React.DragEvent, id: string) => { e.preventDefault(); setDragOverId(id); };
  const handleDrop = (e: React.DragEvent, targetId: string) => {
    e.preventDefault();
    const dragId = dragItemRef.current;
    if (!dragId || dragId === targetId) { setDragOverId(null); return; }
    const updated = [...canvasState];
    const fromIdx = updated.findIndex(c => c.id === dragId);
    const toIdx = updated.findIndex(c => c.id === targetId);
    const [item] = updated.splice(fromIdx, 1);
    updated.splice(toIdx, 0, item);
    pushNewStateToHistory(updated);
    setDragOverId(null);
    dragItemRef.current = null;
    toast.info('Layer reordered.');
  };
  const handleDragEnd = () => { setDragOverId(null); dragItemRef.current = null; };

  // ── FR_05: per-component resize / alignment / spacing ───────────────────────
  const WIDTH_PCT: Record<string, string> = { sm: '40%', md: '60%', lg: '80%', full: '100%' };
  const SPACING_CLASS: Record<string, string> = { compact: 'py-1', normal: 'py-3', spacious: 'py-10' };

  const layoutWrapperStyle = (styles: Record<string, string> = {}): React.CSSProperties => {
    const width = WIDTH_PCT[styles.width] || '100%';
    const align = styles.align || 'center';
    const style: React.CSSProperties = { width };
    if (width !== '100%') {
      if (align === 'center') { style.marginLeft = 'auto'; style.marginRight = 'auto'; }
      else if (align === 'right') { style.marginLeft = 'auto'; }
      else { style.marginRight = 'auto'; }
    }
    return style;
  };

  const updateComponentStyle = (id: string, key: string, value: string) => {
    const updated = canvasState.map(c =>
      c.id === id ? { ...c, styles: { ...(c.styles || {}), [key]: value } } : c
    );
    pushNewStateToHistory(updated);
  };

  const activeComponent = canvasState.find(c => c.id === selectedComponentId);

  return (
    <div className="h-screen bg-[#f1f5f9] flex flex-col pt-16 font-['Inter',_sans-serif]">

      {/* Export Modal */}
      <AnimatePresence>
        {showExportModal && (
          <ExportModal
            canvas={canvasState}
            projectTitle={projectTitle}
            onClose={() => setShowExportModal(false)}
            userTier={userTier}
            onUpgrade={handleUpgrade}
            isUpgrading={isUpgrading}
          />
        )}
      </AnimatePresence>

      {/* ── Toolbar ── */}
      <div className="h-14 bg-white border-b border-gray-200 px-4 flex items-center justify-between z-10 shadow-sm">
        <div className="flex items-center gap-3">
          <button onClick={onBack} className="p-2 hover:bg-gray-100 rounded-lg transition-colors text-gray-600">
            <ChevronLeft className="w-5 h-5" />
          </button>
          <div className="h-6 w-px bg-gray-200" />
          <input
            value={projectTitle}
            onChange={e => setProjectTitle(e.target.value)}
            className="font-bold text-gray-900 bg-transparent border-none outline-none hover:bg-gray-50 focus:bg-gray-50 px-2 py-1 rounded-lg transition-colors text-sm"
          />
        </div>

        <div className="flex items-center gap-2">
          {userTier === 'free' && (
            <div className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold border ${
              usageCount >= FREE_TIER_LIMIT
                ? 'bg-red-50 border-red-200 text-red-700'
                : 'bg-amber-50 border-amber-200 text-amber-700'
            }`}>
              <Zap className="w-3.5 h-3.5" />
              {usageCount}/{FREE_TIER_LIMIT} commands
            </div>
          )}
          {userTier === 'premium' && (
            <div className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-50 border border-blue-200 rounded-lg text-blue-700 text-xs font-bold">
              <Crown className="w-3.5 h-3.5" /> Premium
            </div>
          )}
          <button onClick={handleUndoAction} disabled={historyPointer <= 0}
            className="p-2 hover:bg-gray-100 disabled:opacity-30 rounded-lg text-gray-600" title="Undo">
            <Undo2 className="w-4 h-4" />
          </button>
          <button onClick={handleRedoAction} disabled={historyPointer >= historyStack.length - 1}
            className="p-2 hover:bg-gray-100 disabled:opacity-30 rounded-lg text-gray-600" title="Redo">
            <Redo2 className="w-4 h-4" />
          </button>
          <button
            onClick={() => setTtsEnabled(p => !p)}
            className={`p-2 rounded-lg transition-colors ${ttsEnabled ? 'text-blue-600 bg-blue-50' : 'text-gray-400 hover:bg-gray-100'}`}
            title={ttsEnabled ? 'Disable Voice Feedback' : 'Enable Voice Feedback'}
          >
            {ttsEnabled ? <Volume2 className="w-4 h-4" /> : <VolumeX className="w-4 h-4" />}
          </button>
          <div className="h-6 w-px bg-gray-200 mx-1" />
          <button onClick={handleSaveProject} disabled={isSaving || !projectId}
            className="flex items-center gap-2 bg-gray-800 text-white px-4 py-2 rounded-lg text-sm font-bold hover:bg-gray-700 disabled:opacity-50 transition-colors">
            {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
            Save
          </button>
          <button
            onClick={() => {
              if (canvasState.length === 0) { toast.error('Canvas is empty — add components first.'); return; }
              setShowExportModal(true);
            }}
            className="flex items-center gap-2 bg-[#0052CC] text-white px-4 py-2 rounded-lg text-sm font-bold hover:bg-[#0047b3] transition-colors"
          >
            <Code2 className="w-4 h-4" /> Export Code
          </button>
        </div>
      </div>

      <div className="flex-1 flex overflow-hidden">

        {/* ── Left Panel ── */}
        <div className="w-64 bg-white border-r border-gray-200 flex flex-col overflow-hidden">
          <div className="p-4 flex-1 overflow-y-auto space-y-5">

            {/* Language Toggle */}
            <div>
              <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-2 ml-1">Voice Language</p>
              <div className="grid grid-cols-2 gap-1 bg-gray-100 p-1 rounded-xl">
                {(['English', 'Urdu'] as const).map(lang => (
                  <button key={lang} onClick={() => setLanguage(lang)}
                    className={`py-1.5 text-xs font-bold rounded-lg transition-all ${
                      language === lang ? 'bg-white text-[#0052CC] shadow-sm' : 'text-gray-500'
                    }`}>
                    {lang === 'Urdu' ? 'اردو (Urdu)' : 'English'}
                  </button>
                ))}
              </div>
              {language === 'Urdu' && (
                <p className="text-[10px] text-blue-500 mt-1.5 ml-1">
                  🎙 Gemini AI will transcribe your Urdu speech.
                </p>
              )}
            </div>

            {/* Clarification Alert */}
            {clarificationMessage && (
              <div className="flex items-start gap-2 p-3 bg-amber-50 border border-amber-200 rounded-xl text-xs text-amber-800">
                <AlertCircle className="w-4 h-4 text-amber-500 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-bold mb-0.5">Clarification Needed</p>
                  <p>{clarificationMessage}</p>
                </div>
              </div>
            )}

            {/* Text Command */}
            <div>
              <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-2 ml-1">Text Command</p>
              <form onSubmit={dispatchTextCommand}>
                <textarea
                  value={textCommand}
                  onChange={e => setTextCommand(e.target.value)}
                  onKeyDown={e => {
                    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); dispatchTextCommand(e as any); }
                  }}
                  rows={3}
                  placeholder={
                    language === 'Urdu'
                      ? 'مثلاً: ایک ہیرو سیکشن شامل کریں...'
                      : 'e.g., add a hero section with blue gradient...'
                  }
                  dir={language === 'Urdu' ? 'rtl' : 'ltr'}
                  className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl text-sm outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                />
                <button type="submit" disabled={isProcessingAI || !textCommand.trim()}
                  className="mt-2 w-full bg-[#0052CC] text-white py-2 rounded-xl text-xs font-bold hover:bg-[#0047b3] disabled:opacity-50 transition-colors flex items-center justify-center gap-2">
                  {isProcessingAI
                    ? <><RefreshCw className="w-3.5 h-3.5 animate-spin" /> Processing…</>
                    : 'Generate →'
                  }
                </button>
              </form>
            </div>

            {/* Layers */}
            <div>
              <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-2 ml-1">
                Layers ({canvasState.length})
              </p>
              {canvasState.length === 0 ? (
                <p className="text-xs text-gray-400 italic p-2">No layers yet.</p>
              ) : (
                <div className="space-y-1">
                  {canvasState.map(comp => (
                    <div
                      key={comp.id}
                      draggable
                      onDragStart={() => handleDragStart(comp.id)}
                      onDragOver={e => handleDragOver(e, comp.id)}
                      onDrop={e => handleDrop(e, comp.id)}
                      onDragEnd={handleDragEnd}
                      onClick={() => setSelectedComponentId(comp.id)}
                      className={`w-full flex items-center justify-between p-2 rounded-xl text-sm transition-all cursor-pointer ${
                        dragOverId === comp.id
                          ? 'bg-blue-100 border-2 border-blue-400'
                          : selectedComponentId === comp.id
                          ? 'bg-blue-50 border border-blue-200 text-blue-900 font-medium'
                          : 'hover:bg-gray-50 text-gray-700'
                      }`}
                    >
                      <div className="flex items-center gap-2 flex-1 min-w-0">
                        <GripVertical className="w-3.5 h-3.5 text-gray-300 flex-shrink-0 cursor-grab" />
                        <span className="truncate text-xs">{comp.name}</span>
                      </div>
                      <button
                        onClick={e => { e.stopPropagation(); removeComponent(comp.id); }}
                        className="p-1 text-gray-400 hover:text-red-500 rounded flex-shrink-0"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Clear Canvas */}
            {canvasState.length > 0 && (
              <button
                onClick={() => {
                  if (confirm('Clear all components from canvas? This cannot be undone after save.')) {
                    pushNewStateToHistory([]);
                    setSelectedComponentId(null);
                    toast.info('Canvas cleared.');
                    speakTTS('Canvas cleared.');
                  }
                }}
                className="w-full py-2 text-xs font-bold text-red-500 border border-red-200 rounded-xl hover:bg-red-50 transition-colors"
              >
                Clear Canvas
              </button>
            )}
          </div>
        </div>

        {/* ── Canvas Area ── */}
        <div className="flex-1 relative bg-[#0f172a] overflow-auto flex flex-col p-6 items-center">
          {isProcessingAI && (
            <div className="absolute top-4 left-1/2 -translate-x-1/2 bg-blue-600 text-white px-5 py-2.5 rounded-full text-xs font-bold shadow-xl flex items-center gap-2 z-30">
              <Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating UI…
            </div>
          )}

          <div className="w-full min-h-[600px] bg-white rounded-2xl shadow-2xl relative overflow-hidden border border-gray-800 flex flex-col">
            <div className="absolute inset-0 opacity-[0.02] pointer-events-none"
              style={{ backgroundImage: 'radial-gradient(#000 1px, transparent 1px)', backgroundSize: '24px 24px' }} />

            {canvasState.length === 0 ? (
              <div className="flex-1 flex flex-col items-center justify-center p-12 text-center">
                <div className="w-20 h-20 bg-gray-100 rounded-3xl flex items-center justify-center mb-6">
                  <Mic className="w-10 h-10 text-gray-400" />
                </div>
                <p className="text-gray-600 font-semibold text-lg mb-2">Your canvas is empty</p>
                <p className="text-gray-400 text-sm max-w-sm">
                  Hold the mic and say{' '}
                  <span className="text-blue-500 font-medium">"Add a hero section with a dark gradient"</span>
                </p>
                {language === 'Urdu' && (
                  <p className="text-gray-400 text-sm mt-2">
                    یا اردو میں:{' '}
                    <span className="text-blue-500 font-medium">"ایک ہیرو سیکشن شامل کریں"</span>
                  </p>
                )}
              </div>
            ) : (
              <div className="flex-1 w-full flex flex-col">
                {canvasState.map(comp => (
                  <div
                    key={comp.id}
                    onClick={() => setSelectedComponentId(comp.id)}
                    className={`relative group border-2 transition-colors ${
                      SPACING_CLASS[comp.styles?.spacing] || ''
                    } ${
                      selectedComponentId === comp.id
                        ? 'border-blue-500'
                        : 'border-transparent hover:border-blue-200'
                    }`}
                  >
                    <div
                      style={layoutWrapperStyle(comp.styles)}
                      dangerouslySetInnerHTML={{ __html: sanitizeHTML(comp.htmlContent) }}
                    />
                  </div>
                ))}
              </div>
            )}

            {/* Mic Button */}
            <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-20">
              <button
                type="button"
                aria-label={isListening ? 'Release to generate from your voice command' : 'Hold to speak a voice command'}
                aria-pressed={isListening}
                onMouseDown={activateAudioCaptureStream}
                onMouseUp={terminateAudioCaptureStream}
                onTouchStart={activateAudioCaptureStream}
                onTouchEnd={terminateAudioCaptureStream}
                disabled={isProcessingAI}
                className={`group relative flex items-center gap-3 ${
                  isListening
                    ? 'bg-red-600 scale-105 shadow-red-500/40'
                    : 'bg-[#0052CC] hover:bg-[#0047b3] shadow-blue-500/40'
                } text-white pl-4 pr-6 py-3 rounded-full font-bold shadow-2xl transition-all transform active:scale-95 disabled:opacity-60`}
              >
                <div className="relative">
                  {isListening && (
                    <motion.div animate={{ scale: [1, 1.6, 1], opacity: [0.6, 0, 0.6] }}
                      transition={{ duration: 1.2, repeat: Infinity }}
                      className="absolute inset-0 bg-white rounded-full" />
                  )}
                  <div className="w-8 h-8 bg-white/20 rounded-full flex items-center justify-center">
                    <Mic className="w-4 h-4" />
                  </div>
                </div>
                {isListening ? 'Release to Generate' : isProcessingAI ? 'Processing…' : 'Hold to Speak'}
              </button>
            </div>
          </div>

          {/* Voice feedback waveform */}
          <AnimatePresence>
            {isListening && (
              <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
                className="mt-4 w-full max-w-2xl bg-gray-900 border border-white/10 p-4 rounded-2xl text-center shadow-xl">
                <div className="flex items-center justify-center gap-2 mb-2">
                  <div className="w-2 h-2 bg-red-500 rounded-full animate-pulse" />
                  <span className="text-[10px] text-gray-400 font-bold uppercase tracking-wider">
                    Voice Capture Active — {language}
                  </span>
                </div>
                <div className="flex items-center justify-center gap-1 h-8 mb-2">
                  {[1,2,3,4,5,6,7,8].map(i => (
                    <motion.div key={i}
                      animate={{ height: [8, 24, 12, 28, 10][i % 5] }}
                      transition={{ duration: 0.8, repeat: Infinity, delay: i * 0.1 }}
                      className="w-1 bg-blue-400 rounded-full"
                    />
                  ))}
                </div>
                <p className="text-sm font-medium text-blue-200 min-h-[20px]">{transcription}</p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* ── Right Inspector ── */}
        <div className="w-72 bg-white border-l border-gray-200 flex flex-col overflow-y-auto p-5">
          <div className="flex items-center justify-between pb-4 border-b border-gray-100 mb-5">
            <h3 className="font-bold text-gray-900 uppercase text-xs tracking-widest">Inspector</h3>
            <Settings2 className="w-4 h-4 text-gray-400" />
          </div>

          {activeComponent ? (
            <div className="space-y-4">
              <div>
                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mb-1">Component</label>
                <div className="p-3 bg-gray-50 border border-gray-200 rounded-xl text-sm font-semibold text-gray-800">
                  {activeComponent.name}
                </div>
              </div>
              <div>
                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mb-1">Type</label>
                <div className="p-3 bg-gray-50 border border-gray-200 rounded-xl text-xs text-gray-600 font-mono">
                  {activeComponent.type}
                </div>
              </div>

              {/* FR_05: Layout & Size — manual resize / align / spacing */}
              <div className="border-t border-gray-100 pt-4 space-y-3">
                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block">Layout &amp; Size</label>

                <div>
                  <p className="text-[10px] font-semibold text-gray-500 mb-1">Width</p>
                  <div className="grid grid-cols-4 gap-1 bg-gray-100 p-1 rounded-lg">
                    {([['sm','S'],['md','M'],['lg','L'],['full','Full']] as const).map(([val, lbl]) => (
                      <button key={val}
                        onClick={() => updateComponentStyle(activeComponent.id, 'width', val)}
                        className={`py-1.5 text-[11px] font-bold rounded-md transition-all ${
                          (activeComponent.styles?.width || 'full') === val ? 'bg-white text-[#0052CC] shadow-sm' : 'text-gray-500'
                        }`}>{lbl}</button>
                    ))}
                  </div>
                </div>

                <div>
                  <p className="text-[10px] font-semibold text-gray-500 mb-1">Alignment</p>
                  <div className="grid grid-cols-3 gap-1 bg-gray-100 p-1 rounded-lg">
                    {([['left','Left'],['center','Center'],['right','Right']] as const).map(([val, lbl]) => (
                      <button key={val}
                        onClick={() => updateComponentStyle(activeComponent.id, 'align', val)}
                        className={`py-1.5 text-[11px] font-bold rounded-md transition-all ${
                          (activeComponent.styles?.align || 'center') === val ? 'bg-white text-[#0052CC] shadow-sm' : 'text-gray-500'
                        }`}>{lbl}</button>
                    ))}
                  </div>
                  <p className="text-[9px] text-gray-400 mt-1">Alignment applies when width is below Full.</p>
                </div>

                <div>
                  <p className="text-[10px] font-semibold text-gray-500 mb-1">Spacing</p>
                  <div className="grid grid-cols-3 gap-1 bg-gray-100 p-1 rounded-lg">
                    {([['compact','Compact'],['normal','Normal'],['spacious','Spacious']] as const).map(([val, lbl]) => (
                      <button key={val}
                        onClick={() => updateComponentStyle(activeComponent.id, 'spacing', val)}
                        className={`py-1.5 text-[11px] font-bold rounded-md transition-all ${
                          (activeComponent.styles?.spacing || 'normal') === val ? 'bg-white text-[#0052CC] shadow-sm' : 'text-gray-500'
                        }`}>{lbl}</button>
                    ))}
                  </div>
                </div>
              </div>

              {/* Style suggestions — populate text command box */}
              <div>
                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mb-2">
                  Quick Style Actions
                </label>
                <div className="space-y-1.5">
                  {[
                    `Make the ${activeComponent.name} dark themed`,
                    `Change ${activeComponent.name} background to blue`,
                    `Add shadow and padding to ${activeComponent.name}`,
                    `Make ${activeComponent.name} text larger`,
                    `Make ${activeComponent.name} more colorful`,
                  ].map(suggestion => (
                    <button
                      key={suggestion}
                      onClick={() => {
                        setTextCommand(suggestion);
                        toast.info('Command added to text box. Click Generate to apply.');
                      }}
                      className="w-full text-left text-xs px-3 py-2 bg-gray-50 border border-gray-100 rounded-lg hover:bg-blue-50 hover:border-blue-200 hover:text-blue-700 transition-all text-gray-600"
                    >
                      {suggestion}
                    </button>
                  ))}
                </div>
                <p className="text-[10px] text-gray-400 mt-2 italic">
                  Click to populate text box, then hit Generate.
                </p>
              </div>

              <div>
                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mb-2">Actions</label>
                <button
                  onClick={() => removeComponent(activeComponent.id)}
                  className="w-full bg-red-50 hover:bg-red-100 text-red-600 border border-red-200 font-bold py-2.5 rounded-xl text-xs transition-colors"
                >
                  Delete Component
                </button>
              </div>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="text-center py-6 text-gray-400 text-xs italic">
                Click a component on the canvas to inspect it.
              </div>
              <div className="border-t border-gray-100 pt-4">
                <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-3">Quick Commands</p>
                <div className="space-y-1.5">
                  {[
                    { cmd: 'Add a navbar', desc: 'Navigation bar' },
                    { cmd: 'Add a hero section', desc: 'Hero banner' },
                    { cmd: 'Add a features grid', desc: '3-column features' },
                    { cmd: 'Add a cards row', desc: 'Card components' },
                    { cmd: 'Add a contact form', desc: 'Contact section' },
                    { cmd: 'Add a footer', desc: 'Page footer' },
                  ].map(tip => (
                    <button key={tip.cmd} onClick={() => setTextCommand(tip.cmd)}
                      className="w-full text-left p-2 rounded-lg border border-gray-100 hover:bg-blue-50 hover:border-blue-200 transition-all group">
                      <p className="text-xs font-bold text-gray-700 group-hover:text-blue-700">"{tip.cmd}"</p>
                      <p className="text-[10px] text-gray-400">{tip.desc}</p>
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
