/**
 * zipExport.ts
 * Client-side ZIP generation for multi-page website export.
 * Uses JSZip to bundle one HTML file per page + a shared styles.css.
 *
 * Each HTML file includes:
 *  - Tailwind CDN
 *  - Sticky nav bar with links to other pages
 *  - All canvas sections for that page
 */

import JSZip from 'jszip';

// ─── Types (mirrors Workspace) ────────────────────────────────────────────────
interface CanvasComponent {
  id: string;
  type: string;
  name: string;
  styles: Record<string, string>;
  htmlContent: string;
}

interface ExportPage {
  _id: string;
  name: string;
  slug: string;
  canvasState: CanvasComponent[];
}

// ─── Layout helpers ───────────────────────────────────────────────────────────
const WIDTH_PCT: Record<string, string> = { sm: '40%', md: '60%', lg: '80%', full: '100%' };
const SPACING_PAD: Record<string, string> = {
  compact: '0.25rem 0',
  normal: '0.75rem 0',
  spacious: '2.5rem 0',
};

const wrapperStyle = (styles: Record<string, string> = {}): string => {
  const w = WIDTH_PCT[styles.width] || '100%';
  const parts = [`width:${w}`, `padding:${SPACING_PAD[styles.spacing] || '0.75rem 0'}`];
  if (w !== '100%') {
    const align = styles.align || 'center';
    if (align === 'center') parts.push('margin-left:auto', 'margin-right:auto');
    else if (align === 'right') parts.push('margin-left:auto');
    else parts.push('margin-right:auto');
  }
  return parts.join(';');
};

// ─── Per-page HTML builder ────────────────────────────────────────────────────
const buildPageHTML = (
  page: ExportPage,
  projectTitle: string,
  navLinks: { name: string; filename: string }[],
  currentFilename: string,
  canvasFont = 'Inter',
): string => {
  const navHTML =
    navLinks.length > 1
      ? `  <nav style="position:sticky;top:0;z-index:999;background:rgba(255,255,255,0.95);backdrop-filter:blur(8px);border-bottom:1px solid #e5e7eb;padding:0.75rem 1.5rem;display:flex;align-items:center;gap:1.5rem;">
    <a href="${navLinks[0].filename}" style="font-weight:900;font-size:1rem;color:#1e293b;text-decoration:none;">${projectTitle}</a>
    ${navLinks
      .map(
        l =>
          `<a href="${l.filename}" style="font-size:0.875rem;font-weight:600;text-decoration:none;color:${
            l.filename === currentFilename ? '#2563eb' : '#374151'
          };">${l.name}</a>`,
      )
      .join('\n    ')}
  </nav>`
      : '';

  const sections = page.canvasState
    .map(
      c =>
        `  <!-- ${c.name} -->\n  <div style="${wrapperStyle(c.styles)}">\n    ${c.htmlContent.trim()}\n  </div>`,
    )
    .join('\n\n');

  const gfontsLink = canvasFont !== 'Inter'
    ? `\n  <link rel="preconnect" href="https://fonts.googleapis.com" />\n  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n  <link href="https://fonts.googleapis.com/css2?family=${encodeURIComponent(canvasFont)}:wght@400;600;700&display=swap" rel="stylesheet" />`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${page.name} — ${projectTitle}</title>${gfontsLink}
  <script src="https://cdn.tailwindcss.com"><\/script>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
${navHTML}
${sections || '  <!-- No content on this page yet -->'}
</body>
</html>`;
};

// ─── Shared CSS ───────────────────────────────────────────────────────────────
const buildSharedCSS = (canvasFont = 'Inter'): string => {
  const fontStack = canvasFont !== 'Inter'
    ? `'${canvasFont}', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif`
    : `'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif`;

  return `/* Generated by Speak2Design — https://d1khpu1t6zzts5.cloudfront.net */
/* This project uses Tailwind CSS via CDN. */
/* For production, install Tailwind via npm and remove the CDN script. */

*, *::before, *::after { box-sizing: border-box; }

body {
  margin: 0;
  font-family: ${fontStack};
  -webkit-font-smoothing: antialiased;
}

img { max-width: 100%; height: auto; }

a { color: inherit; }
`;
};

// ─── README ──────────────────────────────────────────────────────────────────
const buildReadme = (projectTitle: string, pages: ExportPage[]): string => `# ${projectTitle}

Generated by **Speak2Design** — AI-powered website builder.

## Files

${pages
  .map((p, i) => {
    const filename = i === 0 ? 'index.html' : `page-${i + 1}.html`;
    return `- \`${filename}\` — ${p.name}`;
  })
  .join('\n')}
- \`styles.css\` — Shared stylesheet

## Usage

1. Open \`index.html\` in any browser.
2. The site uses Tailwind CSS via CDN — no build step required.
3. For production, replace the CDN with a local Tailwind install:
   \`\`\`bash
   npm install tailwindcss
   \`\`\`

## Pages

${pages.map(p => `### ${p.name}\n${p.canvasState.length} section${p.canvasState.length !== 1 ? 's' : ''}`).join('\n\n')}

---
Built with ❤️ using [Speak2Design](https://speak2design.vercel.app)
`;

// ─── Main export function ─────────────────────────────────────────────────────
/**
 * Build and download a ZIP of the entire website.
 *
 * @param pages        All pages with their canvasState already resolved
 *                     (caller must merge in-memory cache before calling)
 * @param projectTitle The project name used as the ZIP filename
 * @param canvasFont   Google Font selected in the toolbar (default 'Inter')
 */
export const downloadWebsiteZip = async (
  pages: ExportPage[],
  projectTitle: string,
  canvasFont = 'Inter',
): Promise<void> => {
  if (pages.length === 0) throw new Error('No pages to export');

  const zip = new JSZip();

  // Build nav link table once
  const navLinks = pages.map((p, i) => ({
    name: p.name,
    filename: i === 0 ? 'index.html' : `page-${i + 1}.html`,
  }));

  // Add one HTML file per page
  pages.forEach((page, i) => {
    const filename = navLinks[i].filename;
    const html = buildPageHTML(page, projectTitle, navLinks, filename, canvasFont);
    zip.file(filename, html);
  });

  // Shared CSS (includes custom font stack)
  zip.file('styles.css', buildSharedCSS(canvasFont));

  // README
  zip.file('README.md', buildReadme(projectTitle, pages));

  // Generate blob + trigger download
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${projectTitle.replace(/\s+/g, '-').toLowerCase() || 'speak2design'}-website.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 10000);
};
